### ISSUE TITLE
Straight with A,2,3,4,5 don't work

### ISSUE THREAD

**Issue by Simi2437** [ishikota/PyPokerEngine#69]
I work right now on a solution for my other problem and found this issue in your code too.

Wright me if you want to see my solution. I can come with a full solution for the hand evaluator ;)

**Comment by Simi2437** [comment]
I have corrected your code in kind of youre Style.

**Comment by Arka2009** [comment]
Hi, it would be very helpful, if you can share your solution.

**Comment by schreven** [comment]
I fixed this on my branch if you're interested. The change is in hand_evaluator.py; Change the function __search_straight to:

    def __search_straight(self, cards):
    bit_memo = reduce(lambda memo, card: memo | 1 << card.rank, cards, 0)
    bit_memo = bit_memo | 2<<(1<<13&1)
    rank = -1
    straight_check = lambda acc, i: acc & (bit_memo >> (r+i) & 1) == 1
    for r in range(1, 11):
      if reduce(straight_check, range(5), True): rank = r+4
    return rank

I just copied the A bit to the 1 bit, and adapted the for loop to start at 1.
For cleanliness I also reduced the size of the for loop to what is necessary (from 14 to 11) and changed the value of the rank to what it is conventionally named in poker (as the top card).

**Comment by elderhaha** [comment]
Still present in 1.0.1, and here is the blast radius.

```
A2345 (wheel)   treys: Straight   PyPokerEngine: HIGHCARD
56789           treys: Straight   PyPokerEngine: STRAIGHT
TJQKA           treys: Straight   PyPokerEngine: STRAIGHT
```

Over 20,000 random showdowns compared against `treys`, **0.71% had the winner
reversed, and every single one involved an unrecognised ace-low straight.** Examples:

```
board 5d 3d Td 9s As    A: 2s 4h (wheel)    B: 8h 2h (high card)   engine awards B
board Ad 5c 3d Kh 4h    A: 9d 2s (wheel)    B: Jd 3c (pair)        engine awards B
board 5s Kc 2s 7s Ad    A: 5d Qc (pair)     B: 3c 4h (wheel)       engine awards A
```

A further 3.40% of showdowns are wrong for an unrelated reason — `eval_hand` packs the
hole-card ranks into the low 8 bits of the score, so pots that should chop never do
(#68).

If your goal is correct showdowns rather than a rewritten evaluator, replacing the
winner selection fixes both issues at once and needs no changes inside the library —
I posted the snippet in #68. It swaps `GameEvaluator.__find_winners_from` for a
`treys`-based version, which also keeps `eval_hand` intact for
`card_utils.estimate_hole_card_win_rate`, which depends on its bit layout.
